src/objects/Shop_Order__c.object
<CustomObject>
    <fields>
        <fullName>Activate_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Activate Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Buyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shop Buyers</relationshipLabel>
        <relationshipName>Shop_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shop Order</label>
    <nameField>
        <label>Shop Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Product__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Image_Path__c</fullName>
        <label>Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <formula>IMAGE(IF(ISBLANK(Image_Path__c), &quot;https://semantic-ui.com/images/wireframe/image.png&quot;,  Image_Path__c), &quot;Image&quot;, 300, 450)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>8</defaultValue>
        <description>available for buy</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Shop Product</label>
    <nameField>
        <label>Shop Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Product_Order__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shop_Order__c</fullName>
        <label>Shop Order</label>
        <referenceTo>Shop_Order__c</referenceTo>
        <relationshipLabel>Shop Product Orders</relationshipLabel>
        <relationshipName>Shop_Product_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shop_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shop Product</label>
        <referenceTo>Shop_Product__c</referenceTo>
        <relationshipLabel>Shop Product Orders</relationshipLabel>
        <relationshipName>Shop_Product_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sum__c</fullName>
        <description>quantity * price</description>
        <label>Sum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>Quantity__c *  Shop_Product__r.Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Shop Product Order</label>
    <nameField>
        <label>Shop Product Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BucketPageController.cls
/**
 * Created by Admin on 3/29/2018.
 */

public with sharing class BucketPageController {
    public Shop_Order__c shopOrder {get; set;}
    public Decimal totalPrice{
        get{
            Decimal price = 0;
            for (Shop_Product_Order__c productOrder: productOrders) {
                price += productOrder.Total_Cost__c;
            }
            return price;
        } set;}
    public List<Shop_Product_Order__c> productOrders{ get; set;}
    public Boolean tryAgain{get; set;}
    public Boolean success{get; set;}

    public BucketPageController(){
        tryAgain = false;
        success = false;
    }

    public void init(){
        initOrder();
        initContact();
        initProductOrders();
    }

    public void initOrder(){
        Cookie cookieID = ApexPages.currentPage().getCookies().get('id');
        List<Shop_Order__c> orders = new List<Shop_Order__c>();

        if(cookieID != null){
            String cookieIDValue = cookieID.getValue();
            orders =
            [
                    SELECT
                            Id
                            , Status__c
                            , Activate_Date__c
                            , Buyer__c
                            , Buyer__r.Id
                            , Buyer__r.LastName
                            , Buyer__r.FirstName
                            , Buyer__r.MailingCity
                            , Buyer__r.MailingStreet
                            , Buyer__r.MobilePhone
                    FROM Shop_Order__c
                    WHERE Id = :cookieID.getValue() AND Status__c = 'New'
            ];
        }

        if (orders.isEmpty()) {
            shopOrder = new Shop_Order__c(Status__c = 'new', Name = 'guest user order');    //хардкод нужно убрать!!!
            insert shopOrder;
            cookieID = new Cookie('id', shopOrder.Id, '/', 10000, false);
            ApexPages.currentPage().setCookies(new Cookie[]{cookieID});
        } else {
            shopOrder = orders[0];
        }
    }

    public void initContact(){
        if (shopOrder.Buyer__c == null) {
            shopOrder.Buyer__r = new Contact(LastName = 'not identified');
            insert shopOrder.Buyer__r;
        }
    }

    public void refreshPrices(){
        for (Shop_Product_Order__c productOrder : productOrders){
            if (productOrder.Quantity__c > productOrder.Shop_Product__r.Quantity__c) {
                productOrder.Quantity__c = productOrder.Shop_Product__r.Quantity__c;
            }
            if (productOrder.Quantity__c < 0) {
                productOrder.Quantity__c = 0;
            }
            productOrder.Sum__c = productOrder.Quantity__c * productOrder.Shop_Product__r.Price__c;
        }
        System.debug(productOrders[0].Quantity__c);
        update productOrders;
    }

    public void initProductOrders(){
        productOrders = [SELECT
                Id
                , Total_Cost__c
                , Quantity__c
                , Sum__c
                , Shop_Product__r.Name
                , Shop_Product__r.Price__c
                , Shop_Product__r.Brand__c
                , Shop_Product__r.Code__c
//                    , Shop_Product__r.Image__c
                , Shop_Product__r.Image_Path__c
                , Shop_Product__r.Quantity__c
        FROM Shop_Product_Order__c
        WHERE Shop_Order__c = :shopOrder.Id
        ];

        for (Shop_Product_Order__c productOrder : productOrders) {
//            if (productOrder.Quantity__c > productOrder.Shop_Product__r.Quantity__c) {
//                productOrder.Quantity__c = productOrder.Shop_Product__r.Quantity__c;
//            }
            productOrder.Sum__c = productOrder.Quantity__c * productOrder.Shop_Product__r.Price__c;
        }
    }

    public void delFromBucket(){
        Id delProdId = System.currentPageReference().getParameters().get('prodID');
        Shop_Product_Order__c delProduct;

        for (Shop_Product_Order__c productOrder : productOrders) { //находим нужный продукт
            if (productOrder.Id.equals(delProdId)) {
                delProduct = productOrder;
                break;
            }
        }
        System.debug(delProdId);

        if (delProduct != null) {
            delete delProduct;
            System.debug('not null');
        }
        initProductOrders();
    }

    public void submit(){
        initProductOrders();
        System.debug(productOrders[0].Quantity__c);
        //сверяем количества с тем, что в базе, если что-то изменилось, то выведем сообщение и снова эту же страницу с обновленными данными
        List<Id> selectedProducts = new List<Id>();
        for (Shop_Product_Order__c productOrder : productOrders) {
            selectedProducts.add(productOrder.Shop_Product__c);
        }
        List<Shop_Product__c> refreshedProducts = [
                SELECT
                        Id
                        , Quantity__c
                FROM Shop_Product__c
                WHERE Id IN :selectedProducts
        ];
        Map<Id, Shop_Product__c> productMap = new Map<Id, Shop_Product__c>(refreshedProducts);

        Boolean valuesValid = true;
        for (Shop_Product_Order__c productOrder : productOrders) {
            //если введенное кол-во больше того, что осталось (данные устарели)
            System.debug(productOrder.Quantity__c);
            if (productOrder.Quantity__c > productMap.get(productOrder.Shop_Product__c).Quantity__c) {
                valuesValid = false;
                break;
            } else {
                productMap.get(productOrder.Shop_Product__c).Quantity__c -= productOrder.Quantity__c;
            }
        }
        if (valuesValid) {
            success = true;
            shopOrder.Status__c = 'Active';
            shopOrder.Name = shopOrder.Buyer__r.FirstName + ' order';
            shopOrder.Buyer__c = shopOrder.Buyer__r.Id;
            update productMap.values();
            update shopOrder.Buyer__r;
            update shopOrder;
            init();
        } else {
            tryAgain = true;
        }

    }

}