src/objects/Shop_Order__c.object
<CustomObject>
    <fields>
        <fullName>Selected_Type__c</fullName>
        <defaultValue>&quot;Laptop&quot;</defaultValue>
        <label>Selected Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shop Order</label>
    <nameField>
        <label>Shop Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Product__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <formula>IMAGE(IF(ISBLANK(Image_Path__c), &quot;https://semantic-ui.com/images/wireframe/image.png&quot;,  Image_Path__c), &quot;Image&quot;, 300, 450)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>8</defaultValue>
        <description>available for buy</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&quot;Other&quot;</defaultValue>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Shop Product</label>
    <nameField>
        <label>Shop Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Product_Order__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shop_Order__c</fullName>
        <label>Shop Order</label>
        <referenceTo>Shop_Order__c</referenceTo>
        <relationshipLabel>Shop Product Orders</relationshipLabel>
        <relationshipName>Shop_Product_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shop_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shop Product</label>
        <referenceTo>Shop_Product__c</referenceTo>
        <relationshipLabel>Shop Product Orders</relationshipLabel>
        <relationshipName>Shop_Product_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Shop Product Order</label>
    <nameField>
        <label>Shop Product Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HomePageController.cls
/**
 * Created by Danil on 28.03.2018.
 */

public with sharing class HomePageController {

//    public final Shop_Product__c shopProduct {get; set;}
    public List<Shop_Product__c> listShopProducts {get; set;}
    public String prevType = 'Laptop';
    public Integer listItems; //the number of objects of the category/type in the org
    public Integer pageSize {get; set;}
    public Integer pageNumber {get; set;}
    public Integer resultSize {
        get {
            return listItems;
        }
    }
    public Boolean hasNext {
        get {
            return pageNumber < Math.ceil(Decimal.valueOf(resultSize).divide(pageSize, 1));
        }
    }
    public Boolean hasPrevious {
        get {
            return pageNumber > 1;
        }
    }
    public Shop_Order__c shopOrder {get; set;}
    public Integer numOfSelected{
        get{
            return [SELECT COUNT() FROM Shop_Product_Order__c WHERE Shop_Order__c = :shopOrder.Id];
        }
        set;}

    //Constructor
    public HomePageController() {
        this.pageSize = 5;
        this.pageNumber = 1;
        this.numOfSelected = 0;
    }

    public void init(){
        checkCookies();
        refreshList();
    }

    public void refreshList() {
        update shopOrder;
        if (shopOrder.Selected_Type__c != prevType) {
            prevType = shopOrder.Selected_Type__c;
            pageNumber = 1;
        }
        listItems = [SELECT count()
        FROM Shop_Product__c
        WHERE Type__c = :shopOrder.Selected_Type__c
        ];

        Integer offset = (pageNumber-1)*pageSize;
        listShopProducts = [SELECT  Name
                , Brand__c
                , Description__c
                , Price__c
                , Quantity__c
                , Image__c
        FROM Shop_Product__c
        WHERE Type__c = :shopOrder.Selected_Type__c
        ORDER BY Name
        LIMIT :pageSize
        OFFSET :offset
        ];

        //If there are no items on the page
        if (listShopProducts.size() == 0 && pageNumber != 1) {
            pageNumber--;
            refreshList();
        }
    }

    public void checkCookies(){
        Cookie cookieID = ApexPages.currentPage().getCookies().get('id');
        List<Shop_Order__c> orders = new List<Shop_Order__c>();

        if(cookieID != null){
            String cookieIDValue = cookieID.getValue();
            orders =
            [
                    SELECT
                            Id
                            , Selected_Type__c
                    FROM Shop_Order__c
                    WHERE Id = :cookieID.getValue() AND Status__c = 'New'
            ];
        }

        if (orders.isEmpty()) {
            shopOrder = new Shop_Order__c(Status__c = 'new', Name = 'guest user order', Selected_Type__c = 'Laptop');    //хардкод нужно убрать!!!
            insert shopOrder;
            cookieID = new Cookie('id', shopOrder.Id, '/', 100000, false);
            ApexPages.currentPage().setCookies(new Cookie[]{cookieID});
        } else {
            shopOrder = orders[0];
        }
    }

    public void next() {
        pageNumber++;
        refreshList();
    }

    public void previous() {
        pageNumber--;
        refreshList();
    }
}