src/objects/Shop_Order__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shop Order</label>
    <nameField>
        <label>Shop Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Product__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>8</defaultValue>
        <description>available for buy</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Shop Product</label>
    <nameField>
        <label>Shop Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Product_Order__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shop_Order__c</fullName>
        <label>Shop Order</label>
        <referenceTo>Shop_Order__c</referenceTo>
        <relationshipLabel>Shop Product Orders</relationshipLabel>
        <relationshipName>Shop_Product_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shop_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shop Product</label>
        <referenceTo>Shop_Product__c</referenceTo>
        <relationshipLabel>Shop Product Orders</relationshipLabel>
        <relationshipName>Shop_Product_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Shop Product Order</label>
    <nameField>
        <label>Shop Product Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProductPageControllerExtension.cls
/**
 * Created by Danil on 29.03.2018.
 */

/**
 * Created by Admin on 3/29/2018.
 */

public with sharing class ProductPageControllerExtension {
    Shop_Product__c prod {get; set;}
    Shop_Order__c order {get; set;}
    public Integer numOfSelected{
        get{
            return [SELECT COUNT() FROM Shop_Product_Order__c WHERE Shop_Order__c = :order.Id];
        }
        set;}

    public ProductPageControllerExtension(ApexPages.StandardController stdController){
        prod = (Shop_Product__c)stdController.getRecord();
    }

    public void initOrder(){
        Cookie cookieID = ApexPages.currentPage().getCookies().get('id');
        List<Shop_Order__c> orders = new List<Shop_Order__c>();

        if(cookieID != null){
            String cookieIDValue = cookieID.getValue();
            orders =
            [
                    SELECT
                            Id
                    FROM Shop_Order__c
                    WHERE Id = :cookieID.getValue()
            ];
        }

        if (orders.isEmpty()) {
            order = new Shop_Order__c(Status__c = 'new', Name = 'guest user order');    //хардкод нужно убрать!!!
            insert order;
            cookieID = new Cookie('id', order.Id, '/', 10000, false);
            ApexPages.currentPage().setCookies(new Cookie[]{cookieID});
        } else {
            order = orders[0];
        }
    }

    public void addToBucket(){
        List<Shop_Product_Order__c> products = [
                SELECT
                        Id
                FROM Shop_Product_Order__c
                WHERE Shop_Order__c = :order.Id AND Shop_Product__c = :prod.Id
        ];

        if (products.isEmpty()) {
            Shop_Product_Order__c newProduct = new Shop_Product_Order__c(Name = prod.Name, Shop_Order__c = order.Id,
                    Shop_Product__c = prod.Id, Quantity__c = 1);
            insert newProduct;
        }
    }
}