src/objects/Shop_Product__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>8</defaultValue>
        <description>available for buy</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <description>total in werehouse</description>
        <label>Total Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Shop Product</label>
    <nameField>
        <label>Shop Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Shop_productHandler.cls
/**
 * Created by Admin on 3/28/2018.
 */

public class Shop_productHandler {
    private static void addStuff(List<Shop_Product__c> newVals){
        for (Shop_Product__c product : newVals) {
            if (product.Total_Quantity__c <= 3) {
                product.Total_Quantity__c += 5;
                product.Quantity__c += 5;
            }
        }
    }

    public static void beforeUpdate(List<Shop_Product__c> newVals){
        addStuff(newVals);
    }
}