src/objects/Shop_Order__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shop Order</label>
    <nameField>
        <label>Shop Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Product__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>8</defaultValue>
        <description>available for buy</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <description>total in werehouse</description>
        <label>Total Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Shop Product</label>
    <nameField>
        <label>Shop Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Product_Order__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shop_Order__c</fullName>
        <label>Shop Order</label>
        <referenceTo>Shop_Order__c</referenceTo>
        <relationshipLabel>Shop Product Orders</relationshipLabel>
        <relationshipName>Shop_Product_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shop_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shop Product</label>
        <referenceTo>Shop_Product__c</referenceTo>
        <relationshipLabel>Shop Product Orders</relationshipLabel>
        <relationshipName>Shop_Product_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Shop Product Order</label>
    <nameField>
        <label>Shop Product Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Shop_OrderHandler.cls
/**
 * Created by Admin on 4/1/2018.
 */

public with sharing class Shop_OrderHandler {

    private static void close(List<Shop_Order__c> newOrders, Map<Id, Shop_Order__c> oldOrders){
        List<Id> closedOrders = new List<Id>();

        for (Shop_Order__c order : newOrders) {
            if (oldOrders.get(order.Id).Status__c == 'Active' && order.Status__c == 'Closed') {
                closedOrders.add(order.Id);
            }
        }

        List<Shop_Product_Order__c> productOrders = [
                SELECT
                        Id
                        , Quantity__c
                        , Shop_Product__r.Total_Quantity__c
                FROM Shop_Product_Order__c
                WHERE Shop_Order__c IN :closedOrders
        ];

        List<Shop_Product__c> updatedProducts = new List<Shop_Product__c>();
        for (Shop_Product_Order__c productOrder : productOrders) {
            productOrder.Shop_Product__r.Total_Quantity__c -= productOrder.Quantity__c;
            updatedProducts.add(productOrder.Shop_Product__r);
        }
        update updatedProducts;

    }

    private static void reject(List<Shop_Order__c> newOrders, Map<Id, Shop_Order__c> oldOrders){
        List<Id> rejectedOrders = new List<Id>();

        for (Shop_Order__c order : newOrders) {
            if (oldOrders.get(order.Id).Status__c == 'Active' && order.Status__c == 'Rejected') {
                rejectedOrders.add(order.Id);
            }
        }
        List<Shop_Product_Order__c> productOrders = [
                SELECT
                        Id
                        , Quantity__c
                        , Shop_Product__r.Quantity__c
                FROM Shop_Product_Order__c
                WHERE Shop_Order__c IN :rejectedOrders
        ];
        List<Shop_Product__c> updatedProducts = new List<Shop_Product__c>();
        for (Shop_Product_Order__c productOrder : productOrders) {
            productOrder.Shop_Product__r.Quantity__c += productOrder.Quantity__c;
            updatedProducts.add(productOrder.Shop_Product__r);
        }
        update updatedProducts;

    }

    private static void preventUpdate(List<Shop_Order__c> newOrders, Map<Id, Shop_Order__c> oldOrders){
        for (Shop_Order__c order : newOrders) {
            if (oldOrders.get(order.id).Status__c == 'Closed' || oldOrders.get(order.id).Status__c == 'Rejected') {
                order.Status__c = oldOrders.get(order.id).Status__c;
            }
        }
    }

    public static void afterUpdate(List<Shop_Order__c> newOrders, Map<Id, Shop_Order__c> oldOrders){
        close(newOrders, oldOrders);
        reject(newOrders, oldOrders);
    }

    public static void beforeUpdate(List<Shop_Order__c> newOrders, Map<Id, Shop_Order__c> oldOrders){
        preventUpdate(newOrders, oldOrders);
    }
}